[BUGFIX] Check for array-key existence
TYPO3GmbH/ext-file-variants pull request #15
Opened 2022-10-10 17:37 UTC by lsascha

Should prevent
```
Warning: Undefined array key
```
warnings

Log:
```´
[ TYPO3\CMS\Core\Error\Exception ]
Warning: Undefined array key "foreign_table" in /var/www/html/web/typo3conf/ext/file_variants/Configuration/TCA/Overrides/manipulation.php line 22

[ TYPO3\CMS\Core\Error\Exception ]
Warning: Undefined array key "languageField" in /var/www/html/web/typo3conf/ext/file_variants/Configuration/TCA/Overrides/manipulation.php line 30

[ TYPO3\CMS\Core\Error\Exception ]
Warning: Undefined array key "sys_language_uid" in /var/www/html/web/typo3conf/ext/file_variants/Configuration/TCA/Overrides/manipulation.php line 32
```

2023-01-19 11:25 UTC, mbrodala commented
Can you simplify this using the null coalescing operator (`??`)? We don't require a PHP version specifically but at minimum TYPO3v10 which itself requires PHP 7.2+

2023-08-30 12:04 UTC, mbrodala commented
@lsascha Can you adjust this as requested?

2023-12-13 09:35 UTC, chrisliquidlight commented
@mbrodala @lsascha Is there any update on this PR, or anything I can contribute? The extension is currently incompatible with PHP 8 until this is added

2023-12-13 09:46 UTC, mbrodala requested changes

2023-12-13 09:46 UTC, mbrodala commented on Configuration/TCA/Overrides/manipulation.php
> +            if (isset($fieldConfig['config']['foreign_table']) && $fieldConfig['config']['foreign_table'] === 'sys_file_reference') {
```suggestion
            if ($fieldConfig['config']['foreign_table'] ?? null === 'sys_file_reference') {
```

2023-12-13 09:46 UTC, mbrodala commented on Configuration/TCA/Overrides/manipulation.php
> +                    }
```suggestion
        $languageField = $GLOBALS['TCA'][$table]['ctrl']['languageField'] ?? null;
        $fieldConfig = $config['columns'][$languageField]['config'] ?? [];
        if ($languageField && isset($fieldConfig['items'])) {
            foreach ($fieldConfig['items'] as $index => $item) {
                if ((int)$item[1] === -1) {
                    unset($GLOBALS['TCA'][$table]['columns'][$languageField]['config']['items'][$index]);
```

2023-12-13 09:47 UTC, merged

2023-12-13 09:47 UTC, mbrodala commented
@chrisliquidlight Done now.

2023-12-13 09:57 UTC, chrisliquidlight commented
@mbrodala Thank you!